### ISSUE TITLE
[BUG] - Can't use the library in v18 

### ISSUE THREAD

**Issue by imadhy** [TimUnderhay/ngx-panzoom#68]
**Describe the bug**
The imports are not good anymore and we have a console error :

![image](https://github.com/TimUnderhay/ngx-panzoom/assets/4727183/21cc9c58-9392-4cae-b04b-e8abcdbf9c6d)

Instead of  : 

`import { PanZoomAPI, PanZoomComponent, PanZoomConfig } from 'ngx-panzoom';`

Here is the console error :

![image](https://github.com/TimUnderhay/ngx-panzoom/assets/4727183/632d9f5a-5ff3-4717-95ee-6034573bdb94)

**To Reproduce**
Just install the v18 of the library.

**Expected behavior**

**Additional context**
The tree files of the installed library is not good :

![image](https://github.com/TimUnderhay/ngx-panzoom/assets/4727183/a7f96d27-3009-4b2b-964c-be786a01d78c)

We have an `ngx-panzoom` folder that shouldn't be here.

I think the library was build and published in a bad environment. Because when I try to build and npm pack it locally, it works great.

**Comment by geromegrignon** [comment]
Breaking changes upon the configuration and the api explained on npm: https://www.npmjs.com/package/ngx-panzoom

**Comment by TimUnderhay** [comment]
Please update to version 19.  It will be the final major version of this library.
