### ISSUE TITLE
Not working panning in Angular 18

### ISSUE THREAD

**Issue by IlyaChubko** [TimUnderhay/ngx-panzoom#69]
Hello!
Not working panning in Angular 18.
Such as on site https://timunderhay.github.io/ngx-panzoom, but old site https://timunderhay.github.io/ngx-panzoom-demo is working and not updated yet

**Comment by TimUnderhay** [comment]
Version 19 has just been released, and panning is confirmed to be working.  Version 19 will be the final major version.
