### ISSUE TITLE
[BUG] - Pinch zoom does not work in mobile

### ISSUE THREAD

**Issue by vikaskandari** [TimUnderhay/ngx-panzoom#70]
Paning works perfectly however pinch zoom is not working as expected, when i put two fingers on container it starts zooming in to maximum zoom then once i start dragging the fingers pinching it then slowly follows the zoom order, however if i lift the fingers and put them pack in pinch gesture  it again resets pan area to maximum.

Possible reason for this behavior could be browsers default pinch and zoom feature for all web pages, i am not entirely sure about this because i have tried using pinch zoom feature without browsers default zoom and it still mulfunctioned.

Here is a minimum code example 

```html
<div [style.height.px]="500">
    <pan-zoom>
        <div class="card" [style.width.px]="794">
            <table>
                <thead>
                    <tr>
                        <th>Item</th>
                        <th>Quantity</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Item 1</td>
                        <td>2</td>
                        <td>$20</td>
                    </tr>
                    <tr>
                        <td>Item 2</td>
                        <td>1</td>
                        <td>$50</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </pan-zoom>
</div>
```

**Comment by TimUnderhay** [comment]
There are no plans to add this at present, though as the readme says, I will gladly accept a PR.
